// src/data/jobData.js
const JOBS = [
  {
    id: 1,
    title: "Frontend Developer",
    description: "React Native, REST API, SSO experience required.",
    fullDescription:
      "We are looking for a talented Frontend Developer to build and maintain a modular React Native SDK for embedding into mobile apps. You will be responsible for implementing multilingual and RTL support, integrating secure Single Sign-On (SSO), and designing responsive interfaces for messaging and communication channels.",
    responsibilities: [
      "Develop and maintain a modular React Native SDK for embedding into mobile apps",
      "Implement multilingual and RTL (Right-to-Left) UI support",
      "Integrate secure Single Sign-On (SSO) functionality",
      "Design responsive interfaces for messaging and communication channels",
      "Follow security best practices to ensure safe handling of user data",
      "Collaborate with cross-functional teams (backend, UX, QA) for integration and testing",
      "Maintain technical documentation and assist in knowledge transfer",
    ],
    qualificationRequired: "Graduation",
    basicQualifications: [
      "Minimum 2 years of experience in React Native development",
      "Proficiency in JavaScript/TypeScript",
      "Experience with REST API integration",
      "Knowledge of Git version control",
      "Understanding of SSO and authentication methods (OAuth2, JWT)",
      "Experience with multilingual UI implementation (i18next or similar)",
    ],
    preferredQualifications: [
      "Meta Certified React Native Developer (optional)",
    ],
    location: "Vizag / Hyderabad / Malaysia / Dubai",
    type: "Contract / Full-time",
    salary: "Not disclosed",
    experience: "2+ years",
    skills: ["React Native", "JavaScript", "TypeScript", "REST APIs", "OAuth2", "JWT", "i18next", "Git"],
    companyName: "GlobalTech Solutions",
    postedDate: "2025-04-01",
    deadline: "2025-04-30",
    benefits: [
      "Flexible work arrangements",
      "Health insurance coverage",
      "Remote work options",
      "Annual performance bonus",
      "Learning & development allowance",
    ],
  },
  {
    id: 2,
    title: "Backend Developer",
    description: "Node.js, Express, Twilio/WhatsApp API experience needed.",
    fullDescription:
      "As a Backend Developer, you'll be responsible for building and maintaining secure REST APIs to support messaging workflows, integrating third-party services like Twilio and WhatsApp, and routing data securely between frontend applications and Salesforce systems.",
    responsibilities: [
      "Build and maintain secure REST APIs to support messaging workflows",
      "Integrate third-party messaging services (e.g., Twilio, WhatsApp APIs)",
      "Route data securely between frontend applications and Salesforce",
      "Implement logic for service tier differentiation and SLA enforcement",
      "Ensure full compliance with data security and residency regulations",
      "Support incident resolution and monitor API reliability",
    ],
    qualificationRequired: "Graduation",
    basicQualifications: [
      "Minimum 2 years of experience in Node.js development",
      "Experience with Express.js and API development",
      "Familiarity with OAuth2, JWT, and authentication protocols",
      "Secure coding and encryption standards",
      "Experience with Twilio/WhatsApp API integration",
    ],
    preferredQualifications: [
      "Node.js Certified Developer (OpenJS Foundation)",
      "API Design & Development Certification (Postman, Swagger, etc.)",
    ],
    location: "Vizag / Hyderabad / Malaysia / Dubai",
    type: "Contract / Full-time",
    salary: "Not disclosed",
    experience: "2+ years",
    skills: ["Node.js", "Express", "REST APIs", "Twilio", "WhatsApp API", "OAuth2", "JWT"],
    companyName: "GlobalTech Solutions",
    postedDate: "2025-04-05",
    deadline: "2025-05-05",
    benefits: [
      "Comprehensive health insurance",
      "Performance-based bonuses",
      "Opportunity for international client exposure",
      "Free access to tech courses and certifications",
      "Paid time off and flexible PTO policy",
    ],
  },
  {
    id: 3,
    title: "Salesforce Integration Engineer",
    description: "Salesforce Admin, Apex, Twilio integration required.",
    fullDescription:
      "You’ll be responsible for integrating all messaging channels (chat, WhatsApp, email, phone) into Salesforce, configuring workflows, automating ticketing, and ensuring secure integrations with third-party platforms using Salesforce APIs.",
    responsibilities: [
      "Integrate all messaging channels (chat, WhatsApp, email, phone) into Salesforce",
      "Configure Salesforce workflows, ticketing automation, and escalation rules",
      "Map user tiers to service-level agreement (SLA) timers and routing logic",
      "Build real-time dashboards and schedule reports for operational performance",
      "Ensure secure integration with third-party platforms using Salesforce APIs",
      "Collaborate with frontend/backend teams to align data flow and business rules",
    ],
    qualificationRequired: "Graduation",
    basicQualifications: [
      "Minimum 2 years of Salesforce administration and configuration experience",
      "Experience with Salesforce Workflows, Process Builder, Web-to-Case setup",
      "Basic understanding of Apex and REST API usage",
      "Experience integrating Twilio with Salesforce",
      "Salesforce Certified Administrator (essential)",
    ],
    preferredQualifications: [
      "Salesforce Platform App Builder Certification",
      "Twilio Integration Certification (optional)",
    ],
    location: "Vizag / Hyderabad / Malaysia / Dubai",
    type: "Contract / Full-time",
    salary: "Not disclosed",
    experience: "2+ years",
    contractDuration: "3–6 months",
    skills: ["Salesforce", "Workflows", "Apex", "REST API", "Twilio", "Process Builder"],
    companyName: "GlobalTech Solutions",
    postedDate: "2025-04-10",
    deadline: "2025-05-10",
    benefits: [
      "Creative freedom and ownership of design decisions",
      "Flexible work schedule",
      "Access to premium design tools and libraries",
      "Mentorship from senior engineers",
      "Quarterly project reviews",
    ],
  },
  {
    id: 4,
    title: "UX Designer",
    description: "UX research, Figma, accessibility standards required.",
    fullDescription:
      "We’re seeking a passionate UX Designer to create seamless, intuitive, multilingual user interfaces for messaging flows. You will produce wireframes, high-fidelity prototypes, and design specifications while ensuring accessibility and RTL support.",
    responsibilities: [
      "Design seamless, intuitive, multilingual user interfaces for messaging flows",
      "Produce wireframes, high-fidelity prototypes, and design specifications",
      "Ensure compliance with accessibility standards and RTL support",
      "Incorporate secure interaction flows (e.g., login, verification, permissions)",
      "Conduct usability testing and incorporate feedback iteratively",
      "Support developers to ensure accurate design implementation",
    ],
    qualificationRequired: "Graduation",
    basicQualifications: [
      "Minimum 2 years of UX design experience",
      "Proficiency in UX research and wireframing tools (Figma, Adobe XD, Sketch)",
      "Experience in responsive and mobile-first design",
      "Strong understanding of usability and accessibility principles",
      "Ability to create interactive prototypes and interaction designs",
    ],
    preferredQualifications: [
      "Google UX Design Certificate",
      "Nielsen Norman Group UX Certification (optional)",
    ],
    location: "Vizag / Hyderabad / Malaysia / Dubai",
    type: "Contract / Full-time",
    salary: "Not disclosed",
    experience: "2+ years",
    skills: ["Figma", "Adobe XD", "Sketch", "Wireframing", "Prototyping", "Accessibility", "RTL Support"],
    companyName: "GlobalTech Solutions",
    postedDate: "2025-04-15",
    deadline: "2025-05-15",
    benefits: [
      "Flexible work hours",
      "Remote-friendly environment",
      "Premium design tool subscriptions",
      "UX mentorship opportunities",
      "Quarterly creative workshops",
    ],
  },
  {
    id: 5,
    title: "Native Mobile Developer (iOS/Android)",
    description: "Java/Kotlin, Swift, React Native bridge experience needed.",
    fullDescription:
      "You’ll support React Native SDK integration with native Android and iOS features, manage device permissions and notifications, ensure app security, and optimize performance across platforms.",
    responsibilities: [
      "Support React Native SDK integration with native Android and iOS features",
      "Manage device permissions, notifications, and OS-specific behaviors",
      "Ensure app security, including secure storage and data protection",
      "Optimize performance for each platform and troubleshoot OS-specific bugs",
      "Collaborate on developing native bridges if required (e.g., for push notifications)",
    ],
    qualificationRequired: "Graduation",
    basicQualifications: [
      "Minimum 2 years of experience with native Android (Java/Kotlin) and iOS (Swift/Objective-C)",
      "Experience integrating native modules with React Native",
      "Knowledge of device security and push notification handling",
      "Experience with version control and build automation",
    ],
    preferredQualifications: [
      "Apple Certified iOS Developer (optional)",
    ],
    location: "Vizag / Hyderabad / Malaysia / Dubai",
    type: "Contract / Full-time",
    salary: "Not disclosed",
    experience: "2+ years",
    skills: ["Android", "iOS", "Kotlin", "Swift", "React Native", "Push Notifications", "Security"],
    companyName: "GlobalTech Solutions",
    postedDate: "2025-04-20",
    deadline: "2025-05-20",
    benefits: [
      "Competitive compensation package",
      "Health and wellness programs",
      "Mobile development hackathons",
      "Device stipends for development",
      "International collaboration opportunities",
    ],
  },
];

export default JOBS;